title: ElephantMFA
description: The documentation for ElephantMFA
logo: assets/img/logo.svg
show_downloads: false
sass:
  style: compact # possible values: nested expanded compact compressed
  sass_dir: _sass
sections:
  - title: Getting Started
    prefix: getting-started
    pages:
      - title: Installation
        url: installation
      - title: Directory Structure
        url: directory-structure
      - title: Deployment
        url: deployment
  - title: The Basics
    prefix: the-basics
    pages:
      - title: Filters
        url: filters
      - title: SpamAssassin
        url: spamassassin
      - title: ClamAV
        url: clamav
      - title: Pattern Matching
        url: pattern-matching
